### ISSUE TITLE
Vnstat2

### ISSUE THREAD

**Issue by maghuro** [de-vnull/vnstat-on-merlin#17]
![Screenshot_2021-07-09-20-47-18-778_com google android gm](https://user-images.githubusercontent.com/1546139/125129139-e72d1480-e0f6-11eb-84ba-64c62a727826.jpg)

I just updated to latest commit on GitHub, something wrong with hourly image...

**Comment by jackyaz** [comment]
fixed in https://github.com/de-vnull/vnstat-on-merlin/commit/98d8349a47a24606d990ad60b9e732f93460405a
