### ISSUE TITLE
Multible Interfaces

### ISSUE THREAD

**Issue by trackhacs** [de-vnull/vnstat-on-merlin#26]
cool addon.

I would like to use vnstat to also monitor the internal interfaces (ethx   ... wlan).

would it be enough to add those interface to vnstat.conf - or would it brake your internal web interface ?

**Comment by de-vnull** [comment]
There are plenty of vnstat (linux) postings that would imply that you can monitor most any interface available (e.g., https://www.techrepublic.com/article/how-to-monitor-network-traffic-with-linux-and-vnstat/) but I never tried it nor was it a feature considered for vnStat-on-Merlin. I initially developed this to track and warn as I approached the limits Comcast put on our internet package.

For periodically checking internal data transfer I use nload (with -m). Scroll using the arrow keys to see all the interfaces.
