### ISSUE TITLE
No addons

### ISSUE THREAD

**Issue by endlingzyb** [de-vnull/vnstat-on-merlin#27]
RT-AC86U Asus-Merlin 386.7 and amtm version  is 3.4.
There is no addons after I installed Vnstat on Merlin with amtm menu.
![image](https://user-images.githubusercontent.com/52320305/212526382-1b9baf0f-2495-4ac9-9dab-4059dadd477c.png)
![image](https://user-images.githubusercontent.com/52320305/212526435-496ece5a-e78c-400e-88ef-711bc1c36496.png)
How should I solve this problem?
Please help me. Thanks a lot!

**Comment by jackyaz** [comment]
koolshare is unsupported

**Comment by endlingzyb** [comment]
I download shared-jy and tried these commands then it works.
![image](https://user-images.githubusercontent.com/52320305/212540767-81ee12bc-85c5-4624-abc9-f8a408cb89b2.png)

![image](https://user-images.githubusercontent.com/52320305/212540320-df6971a7-c31d-40bd-9047-e9f2cc27b50d.png)

**Comment by de-vnull** [comment]
As Jack notes, this is an unknown and therefore unsupported firmware. There is nothing I can do to provide any additional recommendations. Closing this ticket.
